#pragma once

#include <plog/Log.h>

#include <nabto/webrtc/device.hpp>

#define NABTO_SIGNALING_LOGV PLOGV_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGD PLOGD_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGI PLOGI_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGW PLOGW_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGE PLOGE_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGF PLOGF_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
#define NABTO_SIGNALING_LOGN PLOGN_(nabto::webrtc::SIGNALING_LOGGER_INSTANCE_ID)
