name: Build examples

on: push

env:
  VCPKG_BINARY_SOURCES: "clear;x-aws,s3://vcpkg-build-cache-us-east-1,readwrite"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-cpp-examples:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-15, ubuntu-24.04 ]
        include:
          - os: ubuntu-24.04
          - os: macos-15
    timeout-minutes: 30
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         submodules: recursive
         fetch-depth: 0
     - name: Build
       run: cmake --workflow --preset release
       working-directory: examples/libdatachannel
