name: Build And Test

on: push

env:
  VCPKG_BINARY_SOURCES: "clear;x-aws,s3://vcpkg-build-cache-us-east-1,readwrite"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-test-cpp:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ macos-15, ubuntu-24.04 ] #, windows-2022
        include:
          # - os: windows-2022
          #   build_command: cmake --build build-dir --parallel --target install
          - os: ubuntu-24.04
            # 2024-05-29: The ubuntu build started failing with: "Received request to deprovision: The request was cancelled by the remote provider." so we try make without parallellism like with macos
            build_command: cmake --workflow --preset release
          - os: macos-15
            # 2024-01-05: Sometimes mac fails on github actions when doing builds so we use make without parallellism directly, since we hope that fixes the unknown problem.
            build_command: cmake --workflow --preset release
    timeout-minutes: 30
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
       with:
         submodules: recursive
         fetch-depth: 0
     - name: Build and unittest
       run: cmake --workflow --preset test
       working-directory: sdk

     - uses: oven-sh/setup-bun@v2

     - name: Install integration test server
       run: bun install
       working-directory: integration_test_server

     - name: Start integration test server
       run: bun dev &
       working-directory: integration_test_server

     - name: Integration test run
       run: ./build/test/nabto_integration_test
       working-directory: sdk
